# Generated by Django 5.0.2 on 2024-02-18 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата производства продукта'),
        ),
    ]
