# Generated by Django 5.0.2 on 2024-03-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_mailinglog_server_response_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
        migrations.RemoveField(
            model_name='version',
            name='is_current',
        ),
        migrations.AddField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=100),
        ),
    ]
