# Generated by Django 5.0.2 on 2024-03-19 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_version_options_remove_version_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
